// Все строки интерфейса в одном месте.
export const S = {
  coursesTitle: 'Курсы',
  coursesSub: 'Выбирайте курс и двигайтесь по дереву уровней. Каждый пройденный уровень открывает следующие.',
  coursesSearchPlaceholder: 'Поиск по курсам и тегам…',
  coursesEmpty: 'Ничего не найдено. Измените запрос или снимите фильтры.',
  statsCompleted: (n) => `🏁 ${plural(n, 'завершил', 'завершили', 'завершили')}`,
  statsInProgress: (n) => `👥 ${plural(n, 'проходит', 'проходят', 'проходят')}`,
  levelsOf: (done, total) => `${done}/${total} уровней`,
  courseCrumb: 'Курсы',
  treeHint: 'Проходите уровни по порядку — каждый открывает следующие. Пунктирные уровни необязательные, но дают дополнительный XP.',
  progress: 'прогресс',
  legendDone: 'пройден',
  legendAvailable: 'доступен',
  legendLocked: 'закрыт',
  legendBonus: 'бонусная ветка',
  youAreHere: '← вы здесь',
  mapZoomIn: 'Приблизить',
  mapZoomOut: 'Отдалить',
  mapFit: 'Вся карта',
  mapToCurrent: 'К текущему уровню',
  lockedAfter: (titles) => `откроется после: ${titles}`,
  optionalLevel: 'необязательный уровень',
  tabLesson: 'Урок',
  tabQuiz: 'Тест',
  tabTasks: 'Задачи',
  navToLesson: '← К уроку',
  navToQuiz: 'К тесту →',
  navToQuizBack: '← К тесту',
  navToTasks: 'К задачам →',
  levelEyebrow: (xp) => `уровень · +${xp} xp`,
  bonusEyebrow: (xp) => `бонусный уровень · +${xp} xp`,
  quizPassed: 'Тест пройден',
  quizCheck: 'Проверить ответы',
  quizRetry: 'Попробовать снова',
  quizScore: (got, total) => `результат: ${got}/${total}`,
  quizNeed: (need) => ` · нужно ${need}`,
  quizEmpty: 'В этом уровне нет теста — переходите к задачам.',
  questionNum: (n) => `Вопрос ${n}`,
  qTypeSingle: 'один вариант',
  qTypeMulti: 'несколько вариантов',
  qTypeOutput: 'что выведет код',
  qTypeBlank: 'заполните пропуск',
  outputPlaceholder: 'точный вывод программы, каждая строка — с новой…',
  blankPlaceholder: 'ваш ответ…',
  tasksEmpty: 'В этом уровне нет задач по коду.',
  taskDone: (attempts) => `✓ решена · ${plural(attempts, 'попытка', 'попытки', 'попыток')}`,
  taskUnit: 'unit-тесты',
  taskIO: 'ввод/вывод',
  taskBonus: 'бонус',
  run: '▶ Проверить',
  running: 'Компилируем…',
  reset: 'Сбросить к заготовке',
  resetConfirm: 'Заменить ваш код заготовкой задачи?',
  draftSaved: 'черновик сохранён ✓',
  draftSaving: 'сохраняем…',
  examples: 'примеры тест-кейсов',
  exInput: 'ввод', exOutput: 'ожидаемый вывод', exName: 'название',
  compileError: 'ошибка компиляции',
  expected: 'ожидалось',
  actual: 'получено',
  hiddenTest: 'скрытый',
  timeoutNote: 'превышен лимит времени',
  statusFailed: 'есть проваленные тесты',
  statusPassed: 'все тесты пройдены',
  levelDone: (xp) => `Уровень пройден! +${xp} XP`,
  levelDoneUnlocked: 'Открылись новые уровни — загляните в дерево курса.',
  toTree: 'К дереву курса →',
  lockedTitle: 'Уровень пока закрыт',
  lockedBody: 'Сначала пройдите предыдущие уровни ветки.',
  backToTree: '← к дереву курса',
  notFound: 'Страница не найдена',

  // авторизация
  loginTitle: 'Вход в GoPractice',
  loginSub: 'Личный прогресс, ачивки и наставник — после входа.',
  username: 'Имя пользователя',
  password: 'Пароль',
  loginBtn: 'Войти',
  registerBtn: 'Зарегистрироваться',
  switchToRegister: 'Нет аккаунта? Регистрация',
  switchToLogin: 'Уже есть аккаунт? Вход',
  firstUserNote: 'Первый зарегистрированный пользователь становится администратором.',
  logout: 'Выйти',
  adminLink: 'Админка',
  profileLink: 'Кабинет',

  // workspace (широкий экран уровня)
  wsTheory: 'Теория',
  zoneIDE: 'IDE',
  zoneNotes: 'Заметки',
  ideNoTask: 'Выберите задачу в списке слева — здесь откроется редактор с её заготовкой.',
  ideNoTasks: 'В этом уровне нет задач по коду — справа доступны только заметки.',
  splitterTitle: 'Перетащите, чтобы изменить ширину панелей (двойной клик — сброс)',
  notesPreview: 'Предпросмотр',
  notesEdit: 'Редактор',
  noteSaved: 'заметка сохранена ✓',
  notesPlaceholder: 'Записывайте сюда мысли по уроку — Markdown поддерживается:\n\n# Заголовок\n- список\n`код`',

  // подсказки
  hintButton: (n, total) => `Подсказка ${n}/${total}`,
  hintsTitle: 'Подсказки',

  // чат
  mentor: 'Наставник',
  mentorThinking: 'наставник думает…',
  mentorPlaceholder: 'Спросите про теорию или попросите подсказку…',
  mentorSend: 'Отправить',
  mentorClear: 'очистить диалог',
  mentorAskTask: 'спросить наставника',
  mentorTaskContext: (title) => `Вопрос про задачу «${title}»`,
  mentorEmpty: 'Задайте вопрос по уроку — наставник объяснит и наведёт на решение, но не решит за вас.',

  // кабинет
  profileTitle: 'Личный кабинет',
  statXP: 'опыта',
  statLevels: 'уровней пройдено',
  statTasks: 'задач решено',
  statQuizzes: 'тестов сдано',
  achievementsTitle: 'Ачивки',
  notesTitle: 'Заметки',
  registeredAt: (d) => `с нами с ${d}`,
  newAchievement: 'Новая ачивка!',

  // админка
  adminCoursesTitle: 'Курсы (админка)',
  adminNewCourse: 'Новый курс',
  adminNewLevel: 'Новый уровень',
  adminNewTask: 'Новая задача',
  adminSave: 'Сохранить',
  adminDelete: 'Удалить',
  adminDeleteConfirm: (what) => `Удалить ${what}? Это действие необратимо (прогресс пользователей останется).`,
  adminSaved: 'Сохранено ✓',
  adminValidationErrors: 'Ошибки валидации — изменения откатились:',
  adminTabMeta: 'Мета',
  adminTabLesson: 'Урок',
  adminTabQuiz: 'Тест',
  adminTabTasks: 'Задачи',
  adminPreview: 'Превью',
  adminUploadImage: 'Загрузить картинку',
};

export function plural(n, one, few, many) {
  const m10 = n % 10, m100 = n % 100;
  if (m10 === 1 && m100 !== 11) return `${n} ${one}`;
  if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return `${n} ${few}`;
  return `${n} ${many}`;
}
